### ISSUE TITLE
채팅 기능 구현 - 웹소켓 적용

### ISSUE THREAD

**Issue by Hong-min-seok** [Hyundai-IT-E-Team4/where_is_my_room#14]
1. 웹소켓을 사용한 실시간 채팅
2. 새로운 메세지 도착 시 리스트 맨 위에 표시
3. 채팅 사용자의 닉네임과 프로필 사진 표시
4. 웹소켓 handshake 적용
5. servlet-context, loot-context 수정됨

**Comment by Hanseunghoon** [comment]
pr
